Q1. arange(), reshape() 이용 1차원 2차원 3차원 배열 생성

In [1]:
import numpy as np
ar = np.arange(10)
ar1 = ar.reshape(-1,)
ar2 = ar.reshape(2,-1)
ar3 = ar.reshape(-1,2,5)
print(ar1)
print(ar2)
print(ar3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[[0 1 2 3 4]
  [5 6 7 8 9]]]

Q2. reshape(-1,-1)을 이용 1차원을 2차원, 3차원으로 2차원을 1차원 3차원으로 3차원을 1차원 2차원으로 변환

In [4]:
# 리스트와 모습은 거의 비슷하지만 튜플에서는 리스트와 다른 2가지 차이점을 찾아볼 수 있다.
# t2 = (1,)처럼 단지 1개의 요소만을 가질 때는 요소 뒤에 콤마(,)를 반드시 붙여야 한다는 것과
# t4 = 1, 2, 3처럼 괄호( )를 생략해도 무방하다는 점이다.
ar1 = np.arange(10)
ar12 = ar1.reshape(2,-1)
ar13 = ar1.reshape(-1,2,5)
print(ar1)
print(ar12)
print(ar13)
print()
ar2 = np.arange(10).reshape(2,5)
ar21 = ar2.reshape(-1,)
ar23 = ar2.reshape(-1,2,5)
print(ar2)
print(ar21)
print(ar23)
print()
ar3 = np.arange(10).reshape(-1,2,5)
ar31 = ar3.reshape(-1,)
ar32 = ar3.reshape(2,-1)
print(ar3)
print(ar31)
print(ar32)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[[0 1 2 3 4]
  [5 6 7 8 9]]]

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]
[[[0 1 2 3 4]
  [5 6 7 8 9]]]

[[[0 1 2 3 4]
  [5 6 7 8 9]]]
[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]

Q3. 1차원 배열을 실수형으로 변환

In [5]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# A.
ar_float = ar.astype('float64')
ar_float

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

Q4. 1차원 배열의 dtype을 확인

In [12]:
print(ar_float, ar_float.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64

Q5. 주어진 배열에서 음수 값을 모두 0으로 변경하세요.

arr = np.array([-5, -3, -1, 0, 1, 3, 5])

In [17]:
import numpy as np
arr = np.array([-5, -3, -1, 0, 1, 3, 5])
np.where(arr < 0, 0, arr)
# arr[arr < 0] = 0
# arr

array([0, 0, 0, 0, 1, 3, 5])

Q6. 1 ~ 100 까지 배열에서 3의 배수인 것만을 출력

In [18]:
a1 = np.arange(100)
a2 = a1[a1 % 3 ==0]
a2

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

Q7. 1 ~ 100 까지 배열에서 5의 배수이면서 2의 배수인 것만을 출력

In [19]:
import numpy as np
a1 = np.arange(100)
a2 = a1[(a1 % 5 ==0) & (a1 % 2==0)]
a2

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

Q8. 1 ~ 100 까지 배열에서 3의 배수이거나 5의 배수인 것만을 출력

In [20]:
import numpy as np
a1 = np.arange(100)
# print(a1)

a2 = a1[(a1 % 3 ==0) | (a1 % 5==0)]
a2

array([ 0,  3,  5,  6,  9, 10, 12, 15, 18, 20, 21, 24, 25, 27, 30, 33, 35,
       36, 39, 40, 42, 45, 48, 50, 51, 54, 55, 57, 60, 63, 65, 66, 69, 70,
       72, 75, 78, 80, 81, 84, 85, 87, 90, 93, 95, 96, 99])

Q9. 101 ~ 150 사이의 정수를 랜덤하게 추출, 2행 5열 다차원 배열을 생성 후 전치하세요

In [21]:
a = np.random.randint(101,151,size=(2,5))
a.T

array([[106, 120],
       [128, 135],
       [109, 138],
       [138, 125],
       [119, 144]])

Q10. 표준정규분포로 구성된 5행 5열 다차원 배열을 생성하세요.

In [22]:
np.random.randn(5,5)

array([[ 0.14589216, -1.07087081,  2.03527145,  1.23255071,  0.8498032 ],
       [-0.56064004, -1.58755811, -1.81424659,  1.2743466 ,  1.23080338],
       [ 2.16127125, -0.74816383,  1.14306832,  0.11653791,  0.90417687],
       [ 0.37011457,  0.13003243,  0.33751541, -1.85379035, -0.52348924],
       [ 0.1511893 , -0.46075771,  0.4861184 ,  0.56110896, -0.44634275]])

Q11. original_array를 1차원 배열로 변환하여 출력하세요.

In [ ]:
original_array = np.array([[1, 2, 3], [4, 5, 6]])

In [24]:
import numpy as np

original_array = np.array([[1, 2, 3], [4, 5, 6]])
# flattened_array = original_array.flatten()
flattened_array = original_array.reshape(-1)
print(flattened_array)

[1 2 3 4 5 6]

Q12. 주어진 2차원 배열에서 첫 번째 행을 view로 생성하고, 이 view를 수정하여 원본 배열에 반영되도록 하세요.

original_array = np.array([[1, 2, 3], [4, 5, 6]])

In [25]:
import numpy as np

# 2차원 배열 생성
original_array = np.array([[1, 2, 3], [4, 5, 6]])

# 첫 번째 행을 view로 생성
row_view = original_array[0, :]

# view를 수정
row_view[0] = 10

# 결과 확인
print("Original Array:")
print(original_array)
print("Row View:")
print(row_view)

Original Array:
[[10  2  3]
 [ 4  5  6]]
Row View:
[10  2  3]

Q13. 주어진 3차원 배열에서 첫 번째 2차원 배열을 view로 생성하고, 이 view를 수정하여 원본 배열에 반영되도록 하세요.

original_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [26]:
import numpy as np

# 3차원 배열 생성
original_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# 첫 번째 2차원 배열을 view로 생성
slice_view = original_array[0, :, :]

# view를 수정
slice_view[0, 0] = 20

# 결과 확인
print("Original Array:")
print(original_array)
print("Slice View:")
print(slice_view)

Original Array:
[[[20  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Slice View:
[[20  2  3]
 [ 4  5  6]]

Q14. 주어진 2차원 배열을 1차원 배열 view로 reshape하고, 이 view를 수정하여 원본 배열에 반영되도록 하세요.

original_array = np.array([[1, 2, 3], [4, 5, 6]])

In [27]:
import numpy as np

# 2차원 배열 생성
original_array = np.array([[1, 2, 3], [4, 5, 6]])

# 1차원 배열 view로 reshape
reshaped_view = original_array.reshape(-1)

# view를 수정
reshaped_view[0] = 100

# 결과 확인
print("Original Array:")
print(original_array)
print("Reshaped View:")
print(reshaped_view)

Original Array:
[[100   2   3]
 [  4   5   6]]
Reshaped View:
[100   2   3   4   5   6]

Q15. np.ones((10,10))을 아래와 같이 출력하세요.
```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
 ```

In [28]:
arr=np.ones((10,10))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

Q16. Q. 1 ~ 100을 아래와 같이 출력하세요.

```
[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]]
 ```

In [29]:
idx = np.arange(1,101).reshape(10,10)
ar =[]
for i in range(10):
    if i % 2 == 1:
        idx[i] = idx[i][::-1]
        ar.append(idx[i])
    else:
        idx[i] = idx[i]
        ar.append(idx[i])
ar = np.array(ar)
print(ar,type(ar))

[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]] <class 'numpy.ndarray'>

Q17. np.ones((5,5))을 아래와 같이 출력하세요.
```
[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]]
```

In [30]:
# 5x5 크기의 배열에 0으로 채워진 2칸 두께의 패딩을 적용하여 9x9 크기의 배열을 생성
z = np.ones((5,5))
np.pad(z, pad_width=2, mode = 'constant', constant_values = 0 )

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Q18. np.arange(4)을 이용해서 아래와 같이 출력하세요.
```
[[0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 2, 0, 0, 0],
 [0, 0, 3, 0, 0],
 [0, 0, 0, 4, 0]]
```

In [31]:
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

Q19. Q. np.zeros((8,8))을 이용해서 아래와 같이 출력하세요(두가지 방식:인덱싱, tile 함수)
```
[[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0]]
```

In [32]:
import numpy as np
z = np.zeros((8,8),dtype=int)
z[1::2,::2] = 1
z[::2,1::2] = 1
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

Q20. np.arange(336).reshape(6,7,8)에서 100번째 요소의 인덱스를 구하세요.

In [ ]:
import numpy as np

# 배열 생성
array = np.arange(336).reshape(6, 7, 8)

# 100번째 요소의 인덱스 구하기
index_100 = np.unravel_index(99, array.shape)
index_100

(1, 5, 3)

In [34]:
np.arange(336).reshape(6,7,8)

array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31],
        [ 32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55]],

       [[ 56,  57,  58,  59,  60,  61,  62,  63],
        [ 64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 88,  89,  90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111]],

       [[112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127],
        [128, 129, 130, 131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140, 141, 142, 143],
        [144, 145, 146, 147, 148, 149, 150, 151],
        [152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165, 166, 167]],

       [[168, 169, 170, 171, 172, 173, 174, 175],
        [176, 177, 178, 179, 180, 181, 182, 183],
        [184, 185, 186, 187, 188, 189, 190, 191],
        [192, 193, 194, 195, 196, 197, 198, 199],
        [200, 201, 202, 203, 204, 205, 206, 207],
        [208, 209, 210, 211, 212, 213, 214, 215],
        [216, 217, 218, 219, 220, 221, 222, 223]],

       [[224, 225, 226, 227, 228, 229, 230, 231],
        [232, 233, 234, 235, 236, 237, 238, 239],
        [240, 241, 242, 243, 244, 245, 246, 247],
        [248, 249, 250, 251, 252, 253, 254, 255],
        [256, 257, 258, 259, 260, 261, 262, 263],
        [264, 265, 266, 267, 268, 269, 270, 271],
        [272, 273, 274, 275, 276, 277, 278, 279]],

       [[280, 281, 282, 283, 284, 285, 286, 287],
        [288, 289, 290, 291, 292, 293, 294, 295],
        [296, 297, 298, 299, 300, 301, 302, 303],
        [304, 305, 306, 307, 308, 309, 310, 311],
        [312, 313, 314, 315, 316, 317, 318, 319],
        [320, 321, 322, 323, 324, 325, 326, 327],
        [328, 329, 330, 331, 332, 333, 334, 335]]])