## AI기반 챗봇 및 OCR 개발 전문가 과정

#### 교과목명 : m2_programming

- 평가일 : 24.05.10
- 성명 : 김홍준
- 점수 :

※ 문제당 3점으로 채점 60점 + 자유 프로그램 40점

#### 1. numbers 리스트에서 15, 20, 25를 출력하세요.(for문과 if 조건 사용 필수)  
numbers = [5, 15, 6, 20, 7, 25]

In [ ]:
numbers = [5, 15, 6, 20, 7, 25]

print([i for i in numbers if i > 5 and i % 5 == 0])

[15, 20, 25]

#### 2. 아래 list_input에 대해서 주어진 사용자 함수를 일괄적으로 적용할 수 있는 2개의 내장함수를 활용하여 [1, 4, 9, 16, 25], [1, 2]를 출력하는 코드를 작성하세요.

In [ ]:
# 사용자 함수를 선언합니다.
def power(item):
    return item * item
def under_3(item):
    return item < 3

# 변수를 선언합니다.
list_input = [1, 2, 3, 4, 5]

result1 = []
for i in list_input:
    item = power(i)
    result1.append(item)
print(result1)

result2 = []
for i in list_input:
    if under_3(i):
        result2.append(i)
print(result2)

[1, 4, 9, 16, 25]
[1, 2]

#### 3. 정수를 입력하면 짝수 홀수 여부를 반환해주는 프로그램을 작성하세요.(정수를 입력하지 않는 경우에 대해서 예외처리 수행)

In [ ]:
while 1:
    string = input('정수 입력:')
    try:
        number = int(string)
        if number % 2 == 0:
            print('짝수')
        elif number % 2 != 0:
            print('홀수')
    except:
        print('정수가 아닙니다.')
        break

정수 입력:24
짝수
정수 입력:111
홀수
정수 입력:ddd
정수가 아닙니다.

#### 4. a의 b제곱에서 a x b를 뺀 수를 a, b가 아래와 같이 주어졌을 때 람다 함수를 이용해서 구하세요.
a = 2, b = 5 \
a= 5, b = 2

In [ ]:
a= 2
b=5

result = lambda a,b : a**b - a*b

#### 5. 정수를 입력하면 천 단위로 콤마로 구분하여 출력하세요.(정수가 아닌 경우 '정수가 아닙니다.'를 출력)

<!-- 예시)
정수를 입력하세요: 123456789\
123,456,789 -->

In [ ]:
user = input('정수입력:')

try:
    number = int(user)
    print(f'{number:,}')

except:
    print('정수가 아닙니다.')

정수입력:123123123
123,123,123

In [ ]:
num = input('정수를 입력')
if num.isdigit():
    num = num[::-1]
    ret= ''
    for i, c in enumerate(num):
        i += 1
        if i != len(num) and i % 3 == 0:
            ret += (c + ',')
        else:
            ret += c
    ret = ret[::-1]
    print(ret)

정수를 입력123123123
123,123,123

#### 6. example_list = ["요소A", "요소B", "요소C"]를 파이썬 내장함수를 이용하여 아래와 같이 출력하세요.
0번째 요소는 요소A입니다.\
1번째 요소는 요소B입니다.\
2번째 요소는 요소C입니다.

In [ ]:
example_list = ["요소A", "요소B", "요소C"]

for index,value in enumerate(example_list):
    print(f'{index+1}번째 요소는 {value}입니다.')

1번째 요소는 요소A입니다.
2번째 요소는 요소B입니다.
3번째 요소는 요소C입니다.

#### 7. 97을 40으로 나눈 몫과 나머지를 내장함수를 이용하여 구하세요.(튜플로 출력 필수)

In [ ]:
print(divmod(97,40))

(2, 17)

#### 8. list_number = [52, 273, 32, 72, 100]로 변수 선언하고 정수를 입력하면 그 정수 인덱스와 리스트에서 해당하는 값을 출력하는 프로그램을 작성하세요. 단, 모든 예외처리를 수행하며 특히 ValueError와 IndexError는 별도 구분해서 예외처리 한 후 '예외처리 완료'를 마지막으로 출력하세요.

- 4 입력시 \
정수 입력> 4 \
4번째 요소: 100
예외 처리 완료

- 문자 입력시 \
정수 입력> 가 \
정수를 입력해 주세요!
예외 처리 완료

- 5 입력시 \
정수 입력> 5 \
리스트의 인덱스를 벗어났어요!
예외 처리 완료

In [ ]:
list_number = [52, 273, 32, 72, 100]
while 1:
    try:
        user_input = int(input('정수 입력(종료:999)>'))
        if user_input == 999:
            break
        if user_input < 5:
            value = list_number[user_input]
            print(f'{user_input}번째 요소: {value}')

    except IndexError:
        print('리스트의 인덱스를 벗어났어요!')
    except ValueError:
        print('정수를 입력해 주세요!')
    finally:
        print('예외 처리 완료')

정수 입력(종료:999)>0
0번째 요소: 52
예외 처리 완료
정수 입력(종료:999)>3
3번째 요소: 72
예외 처리 완료
정수 입력(종료:999)>5
리스트의 인덱스를 벗어났어요!
예외 처리 완료
정수 입력(종료:999)>kk
정수를 입력해 주세요!
예외 처리 완료
정수 입력(종료:999)>999
예외 처리 완료

#### 9. 사용자로부터 서로 다른 숫자 두 개를 입력받고 첫 번째 와 두 번째중 큰 숫자를 구하는 프로그램을 수행하세요.

In [ ]:
number1 = int(input('숫자1:'))
number2 = int(input('숫자2:'))

if number1 > number2:
    print('큰수 숫자1',number1)
elif number1 < number2:
    print('큰수 숫자2:',number2)
else:
    print('두수는 같다')

숫자1:10
숫자2:9
큰수 숫자1 10

#### 10. 1부터 100까지 아래와 같은 방식으로 2개의 수를 곱해서 가장 큰 수를 구하세요.

 1 * 99 ...99 * 1

In [ ]:
result = 0
for i in range(1,100):
    max_value = i * (100-i)
    if max_value > result:
        result = max_value
print(result)

2500

#### 11. 현재 시간을 년-월-일 시:분:초로 출력하세요.

In [ ]:
from datetime import datetime

now = datetime.now()
time = now.strftime('%Y-%m-%d %H:%M:%S')
print(f'현재 시간 : {time}')

현재 시간 : 2024-05-14 05:58:44

#### 12. 1에서 백만까지 더하는데 걸리는 프로그램 실행 시간을 밀리초(ms) 단위로 구하세요.(1000 밀리초(ms) = 1초)

In [ ]:
import time

result = 0
start = time.time()
for i in range(1,1000001):
    result += i
end = time.time()
print(f'{(end - start)*1000}ms')

133.6967945098877ms

#### 13. [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 'a', 'b', 'c']에서 9와 'a'를 삭제 후 리스트로 출력하세요

In [ ]:
list1 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 'a', 'b', 'c']

list1.remove(9)
list1.remove('a')
print(list1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 'b', 'c']

#### 14. 500 ~ 1000사이의 정수 중 5와 7의 공배수의 합을 구하세요

In [ ]:
result = 0
for i in range(500,1001):
    if i % 5 == 0 and i % 7 == 0:
        result += i
print(result)

10535

#### 15. [    ]을 채워서 아래와 같이 출력하세요.

In [ ]:
numbers = [1,2,3,4,5,6,7,8,9]
# [[1, 4, 7], [2, 5, 8], [3, 6, 9]]

output = [[], [], []]
for number in numbers:
    output[(number-1)%3].append(number)
print(output)

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]

####  16. numbers 내부에 들어 있는 숫자가 몇 번 등장하는지를 출력하는 코드를 작성하세요.
답안 예시:\
{3: 4, 6: 2, 5: 2, 8: 2, 2: 2, 9: 2, 7: 2, 4: 2}

numbers = [3,6,3,5,8,2,9,7,4,3,6,3,5,8,2,9,7,4]

In [ ]:
numbers = [3,6,3,5,8,2,9,7,4,3,6,3,5,8,2,9,7,4]
number_cnt = {}

for i in numbers:
    if i in number_cnt:
        number_cnt[i] += 1
    else:
        number_cnt[i] = 1

print(number_cnt)

{3: 4, 6: 2, 5: 2, 8: 2, 2: 2, 9: 2, 7: 2, 4: 2}

#### 17. 클래스 Country를 완성하여 아래와 같이 출력하세요.

In [ ]:
class Country:
    def __init__(self, name, pop, cap):
        self.name = name
        self.pop = pop
        self.cap = cap
    def desc(self):
        print(f'{self.name}의 인구는 {self.pop}천만명이며 수도는 {self.cap}입니다')

class Korea(Country):
    def desc1(self,gnp):
        self.gnp = gnp
        print('1인당 gnp는 USD %d만입니다.' %self.gnp)

obj = Korea('한국',5,'서울')
obj.desc()
obj.desc1(3)

한국의 인구는 5천만명이며 수도는 서울입니다
1인당 gnp는 USD 3만입니다.

#### 18. 사칙연산을 수행하는  클래스를 작성하여 객체를 만들고 2개의 정수 10, 5를 입력한 후 연산 결과를  포멧을 이용하여 출력하세요.

In [ ]:
class CalF():
    def Sum(self,a,b):
        return a+b
    def Sub(self,a,b):
        return a-b
    def Mul(self,a,b):
        return a*b
    def Div(self,a,b):
        return a/b

obj1 = CalF()
result1 = obj1.Sum(10,5)
result2 = obj1.Sub(10,5)
result3 = obj1.Mul(10,5)
result4 = obj1.Div(10,5)

print(f'더하기: {result1}\n빼기: {result2}\n곱하기: {result3}\n나누기: {result4}')

더하기: 15
빼기: 5
곱하기: 50
나누기: 2.0

#### 19. 올해 경과된 날짜수를 계산하여 출력하세요.

답안 예시:\
오늘은 2024-01-01 이후 127일째 되는 날입니다.

In [ ]:
from datetime import datetime
now = datetime.now()
days = now.strftime('%j')

print(f'오늘은 2024-01-01 이후 {days}일째 되는 날입니다.')

오늘은 2024-01-01 이후 135일째 되는 날입니다.

#### 20. 문자열 리스트 states를 아래 [출력]와 같이 전처리하여 출력하세요
`states = ['   Alabama ', 'Georgia!', 'Georgia', 'georgia', 'FlOrIda',
          'south   carolina##', 'West virginia?']`

[출력]\
['Alabama',\
 'Georgia',\
 'Georgia',\
 'Georgia',\
 'Florida',\
 'South Carolina',\
 'West Virginia']

In [ ]:
import re

states = [' Alabama ', 'Georgia!', 'Georgia', 'georgia', 'FlOrIda', 'south carolina##', 'West virginia?']

def clean_string(strings):
    result = []
    for value in strings:
        value = value.strip()
        value = re.sub('[!#?]','',value)
        value = value.title()
        result.append(value)
    return result
clean_string(states)

['Alabama',
 'Georgia',
 'Georgia',
 'Georgia',
 'Florida',
 'South Carolina',
 'West Virginia']